version: '3.7'

services:
  pokemon-frontend:
    container_name: pokemon-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        SERVER_URL: http://localhost:8085
    ports:
      - '3000:80'